"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.aliasMap = exports.aliasFactoryMap = exports.injectorAware = exports.bootstrap = exports.bootstrapAsync = exports.factoryMethodAsync = exports.customParam = exports.initAsync = exports.customFn = exports.dynamicFactory = exports.override = exports.lazy = exports.alias = exports.aliasFactory = exports.value = exports.objectProperty = exports.factory = exports.dictionary = exports.array = exports.init = exports.factoryMethod = exports.inject = exports.singleton = exports.define = exports.InjectDefineSymbol = exports.Util = exports.Define = exports.createContainer = exports.Injector = void 0;
exports.default = require('./lib/inject');
var inject_1 = require("./lib/inject");
Object.defineProperty(exports, "Injector", { enumerable: true, get: function () { return inject_1.Injector; } });
Object.defineProperty(exports, "createContainer", { enumerable: true, get: function () { return inject_1.createContainer; } });
var define_1 = require("./lib/define");
Object.defineProperty(exports, "Define", { enumerable: true, get: function () { return define_1.Define; } });
var util_1 = require("./lib/util");
Object.defineProperty(exports, "Util", { enumerable: true, get: function () { return util_1.Util; } });
var decorators_1 = require("./lib/decorators");
Object.defineProperty(exports, "InjectDefineSymbol", { enumerable: true, get: function () { return decorators_1.InjectDefineSymbol; } });
Object.defineProperty(exports, "define", { enumerable: true, get: function () { return decorators_1.define; } });
Object.defineProperty(exports, "singleton", { enumerable: true, get: function () { return decorators_1.singleton; } });
Object.defineProperty(exports, "inject", { enumerable: true, get: function () { return decorators_1.inject; } });
Object.defineProperty(exports, "factoryMethod", { enumerable: true, get: function () { return decorators_1.factoryMethod; } });
Object.defineProperty(exports, "init", { enumerable: true, get: function () { return decorators_1.init; } });
Object.defineProperty(exports, "array", { enumerable: true, get: function () { return decorators_1.array; } });
Object.defineProperty(exports, "dictionary", { enumerable: true, get: function () { return decorators_1.dictionary; } });
Object.defineProperty(exports, "factory", { enumerable: true, get: function () { return decorators_1.factory; } });
Object.defineProperty(exports, "objectProperty", { enumerable: true, get: function () { return decorators_1.objectProperty; } });
Object.defineProperty(exports, "value", { enumerable: true, get: function () { return decorators_1.value; } });
Object.defineProperty(exports, "aliasFactory", { enumerable: true, get: function () { return decorators_1.aliasFactory; } });
Object.defineProperty(exports, "alias", { enumerable: true, get: function () { return decorators_1.alias; } });
Object.defineProperty(exports, "lazy", { enumerable: true, get: function () { return decorators_1.lazy; } });
Object.defineProperty(exports, "override", { enumerable: true, get: function () { return decorators_1.override; } });
Object.defineProperty(exports, "dynamicFactory", { enumerable: true, get: function () { return decorators_1.dynamicFactory; } });
Object.defineProperty(exports, "customFn", { enumerable: true, get: function () { return decorators_1.customFn; } });
Object.defineProperty(exports, "initAsync", { enumerable: true, get: function () { return decorators_1.initAsync; } });
Object.defineProperty(exports, "customParam", { enumerable: true, get: function () { return decorators_1.customParam; } });
Object.defineProperty(exports, "factoryMethodAsync", { enumerable: true, get: function () { return decorators_1.factoryMethodAsync; } });
Object.defineProperty(exports, "bootstrapAsync", { enumerable: true, get: function () { return decorators_1.bootstrapAsync; } });
Object.defineProperty(exports, "bootstrap", { enumerable: true, get: function () { return decorators_1.bootstrap; } });
Object.defineProperty(exports, "injectorAware", { enumerable: true, get: function () { return decorators_1.injectorAware; } });
Object.defineProperty(exports, "aliasFactoryMap", { enumerable: true, get: function () { return decorators_1.aliasFactoryMap; } });
Object.defineProperty(exports, "aliasMap", { enumerable: true, get: function () { return decorators_1.aliasMap; } });
//# sourceMappingURL=index.js.map