"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createContainer = exports.InjectDefineSymbol = exports.aliasMap = exports.aliasFactoryMap = exports.injectorAware = exports.bootstrap = exports.bootstrapAsync = exports.factoryMethodAsync = exports.customParam = exports.initAsync = exports.customFn = exports.dynamicFactory = exports.override = exports.lazy = exports.alias = exports.aliasFactory = exports.value = exports.objectProperty = exports.factory = exports.dictionary = exports.array = exports.init = exports.factoryMethod = exports.inject = exports.define = exports.singleton = exports.Util = exports.Define = exports.Injector = void 0;
const inject_1 = require("./lib/inject/inject");
exports.default = require('./lib/inject/inject');
var inject_2 = require("./lib/inject/inject");
Object.defineProperty(exports, "Injector", { enumerable: true, get: function () { return inject_2.Injector; } });
var define_1 = require("./lib/define/define");
Object.defineProperty(exports, "Define", { enumerable: true, get: function () { return define_1.Define; } });
var util_1 = require("./lib/utils/util");
Object.defineProperty(exports, "Util", { enumerable: true, get: function () { return util_1.Util; } });
var singleton_1 = require("./lib/decorators/singleton");
Object.defineProperty(exports, "singleton", { enumerable: true, get: function () { return singleton_1.singleton; } });
var define_2 = require("./lib/decorators/define");
Object.defineProperty(exports, "define", { enumerable: true, get: function () { return define_2.define; } });
var inject_3 = require("./lib/decorators/inject");
Object.defineProperty(exports, "inject", { enumerable: true, get: function () { return inject_3.inject; } });
var factoryMethod_1 = require("./lib/decorators/factoryMethod");
Object.defineProperty(exports, "factoryMethod", { enumerable: true, get: function () { return factoryMethod_1.factoryMethod; } });
var init_1 = require("./lib/decorators/init");
Object.defineProperty(exports, "init", { enumerable: true, get: function () { return init_1.init; } });
var array_1 = require("./lib/decorators/array");
Object.defineProperty(exports, "array", { enumerable: true, get: function () { return array_1.array; } });
var dictionary_1 = require("./lib/decorators/dictionary");
Object.defineProperty(exports, "dictionary", { enumerable: true, get: function () { return dictionary_1.dictionary; } });
var factory_1 = require("./lib/decorators/factory");
Object.defineProperty(exports, "factory", { enumerable: true, get: function () { return factory_1.factory; } });
var objectProperty_1 = require("./lib/decorators/objectProperty");
Object.defineProperty(exports, "objectProperty", { enumerable: true, get: function () { return objectProperty_1.objectProperty; } });
var value_1 = require("./lib/decorators/value");
Object.defineProperty(exports, "value", { enumerable: true, get: function () { return value_1.value; } });
var aliasFactory_1 = require("./lib/decorators/aliasFactory");
Object.defineProperty(exports, "aliasFactory", { enumerable: true, get: function () { return aliasFactory_1.aliasFactory; } });
var alias_1 = require("./lib/decorators/alias");
Object.defineProperty(exports, "alias", { enumerable: true, get: function () { return alias_1.alias; } });
var lazy_1 = require("./lib/decorators/lazy");
Object.defineProperty(exports, "lazy", { enumerable: true, get: function () { return lazy_1.lazy; } });
var override_1 = require("./lib/decorators/override");
Object.defineProperty(exports, "override", { enumerable: true, get: function () { return override_1.override; } });
var dynamicFactory_1 = require("./lib/decorators/dynamicFactory");
Object.defineProperty(exports, "dynamicFactory", { enumerable: true, get: function () { return dynamicFactory_1.dynamicFactory; } });
var customFn_1 = require("./lib/decorators/customFn");
Object.defineProperty(exports, "customFn", { enumerable: true, get: function () { return customFn_1.customFn; } });
var initAsync_1 = require("./lib/decorators/initAsync");
Object.defineProperty(exports, "initAsync", { enumerable: true, get: function () { return initAsync_1.initAsync; } });
var customParam_1 = require("./lib/decorators/customParam");
Object.defineProperty(exports, "customParam", { enumerable: true, get: function () { return customParam_1.customParam; } });
var factoryMethodAsync_1 = require("./lib/decorators/factoryMethodAsync");
Object.defineProperty(exports, "factoryMethodAsync", { enumerable: true, get: function () { return factoryMethodAsync_1.factoryMethodAsync; } });
var bootstrapAsync_1 = require("./lib/decorators/bootstrapAsync");
Object.defineProperty(exports, "bootstrapAsync", { enumerable: true, get: function () { return bootstrapAsync_1.bootstrapAsync; } });
var bootstrap_1 = require("./lib/decorators/bootstrap");
Object.defineProperty(exports, "bootstrap", { enumerable: true, get: function () { return bootstrap_1.bootstrap; } });
var injectorAware_1 = require("./lib/decorators/injectorAware");
Object.defineProperty(exports, "injectorAware", { enumerable: true, get: function () { return injectorAware_1.injectorAware; } });
var aliasFactoryMap_1 = require("./lib/decorators/aliasFactoryMap");
Object.defineProperty(exports, "aliasFactoryMap", { enumerable: true, get: function () { return aliasFactoryMap_1.aliasFactoryMap; } });
var aliasMap_1 = require("./lib/decorators/aliasMap");
Object.defineProperty(exports, "aliasMap", { enumerable: true, get: function () { return aliasMap_1.aliasMap; } });
var decorators_1 = require("./lib/decorators/decorators");
Object.defineProperty(exports, "InjectDefineSymbol", { enumerable: true, get: function () { return decorators_1.InjectDefineSymbol; } });
let createContainer = function () {
    return new inject_1.Injector();
};
exports.createContainer = createContainer;
//# sourceMappingURL=index.js.map